name: Daily Auto Commit

on:
  schedule:
    - cron: "0 1 * * *" # tiap hari jam 08 WIB
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update daily log
        run: |
          echo "Commit on $(date '+%Y-%m-%d %H:%M:%S')" >> daily-log.txt

      - name: Commit & Push
        run: |
          git config user.name "limuwan-g"
          git config user.email "limuwan-g@users.noreply.github.com"
          git add .
          git commit -m "daily commit $(date '+%Y-%m-%d')" || echo "No changes"
          git push
